-- ============================================================================
-- Seed: the twelve projects that shipped with the site.
-- Run AFTER schema.sql. Re-running refreshes texts, never duplicates.
-- ============================================================================

insert into public.projects
  (slug, name, status, platform, category, hue, year, chips, name_i18n, tags_i18n, overview_i18n, sort_order)
values
  ('victoriabank', 'Victoriabank', 'case', 'web', 'product', '#1B3BFF', '2025', '[[0,1],[0,4],[1,0]]'::jsonb, '{}'::jsonb, '{"en":"Banking Platform · Product Design","ru":"Банковская платформа · Продуктовый дизайн","ro":"Platformă bancară · Product Design"}'::jsonb, '{"en":"A closed internal banking platform used by 50+ staff daily. I rebuilt the information architecture from the ground up - clearer data models, role-based navigation, and a checkout-grade approval flow that cut processing time without touching the backend.","ru":"Закрытая внутренняя банковская платформа, которой каждый день пользуются 50+ сотрудников. Я пересобрал информационную архитектуру с нуля - понятные модели данных, ролевая навигация и цепочка согласований уровня чекаута, которая сократила время обработки без изменений в бэкенде.","ro":"O platformă bancară internă, închisă, folosită zilnic de 50+ angajați. Am reconstruit arhitectura informației de la zero - modele de date mai clare, navigare bazată pe roluri și un flux de aprobare la nivel de checkout care a redus timpul de procesare fără să atingă backend-ul."}'::jsonb, 0),
  ('my-doctor-32', 'My Doctor 32', 'live', 'web', 'product', '#00B549', '2023', '[[0,0],[0,6],[1,2]]'::jsonb, '{}'::jsonb, '{"en":"Healthcare Platform · Product Design","ru":"Платформа здравоохранения · Продуктовый дизайн","ro":"Platformă medicală · Product Design"}'::jsonb, '{"en":"A healthcare booking platform where every extra tap costs a patient. I simplified appointment scheduling into a three-step flow and rebuilt the doctor directory so people find the right specialist without calling the front desk.","ru":"Платформа для записи к врачу, где каждый лишний тап стоит пациенту времени. Я упростил запись до трёх шагов и пересобрал каталог врачей - теперь нужного специалиста находят сами, без звонка на ресепшн.","ro":"O platformă de programări medicale unde fiecare tap în plus costă timpul pacientului. Am simplificat programarea la trei pași și am reconstruit catalogul de medici - pacienții găsesc singuri specialistul potrivit, fără telefon la recepție."}'::jsonb, 10),
  ('point-money', 'Point Money', 'case', 'ios', 'product', '#0F0F13', '2024', '[[0,2],[0,3],[1,0]]'::jsonb, '{}'::jsonb, '{"en":"iOS App · Product & UX/UI","ru":"iOS-приложение · Продукт и UX/UI","ro":"Aplicație iOS · Product & UX/UI"}'::jsonb, '{"en":"A money-transfer product built for speed under real financial stakes. I mapped the full send-and-receive flow, prototyped the MVP in Figma, and ran two rounds of usability testing before a single line of code shipped.","ru":"Продукт для денежных переводов, где скорость важна так же, как и деньги пользователей. Я построил весь флоу отправки и получения, спрототипировал MVP в Figma и провёл два раунда юзабилити-тестирования до того, как написали первую строчку кода.","ro":"Un produs de transfer de bani unde viteza contează la fel de mult ca banii utilizatorilor. Am mapat tot fluxul de trimitere și primire, am prototipat MVP-ul în Figma și am rulat două runde de testare de uzabilitate înainte să scriem prima linie de cod."}'::jsonb, 20),
  ('zazitex', 'Zazitex.com', 'live', 'web', 'product', '#1B3BFF', '2024', '[[0,7],[1,2],[1,5]]'::jsonb, '{}'::jsonb, '{"en":"Agency Website · UX/UI","ru":"Сайт агентства · UX/UI","ro":"Site de agenție · UX/UI"}'::jsonb, '{"en":"The agency''s own front door. A wireframe-first rebuild that turned a static brochure site into a lead-generating page - faster load, clearer service pages, and a handoff-ready component library for the dev team.","ru":"Собственный сайт агентства. Пересборка с вайрфреймов - из статичной визитки получилась страница, которая реально приводит заявки: быстрее загрузка, понятные страницы услуг и библиотека компонентов, готовая к передаче в разработку.","ro":"Site-ul propriu al agenției. O reconstrucție pornind de la wireframe-uri - dintr-o broșură statică a ieșit o pagină care chiar aduce lead-uri: încărcare mai rapidă, pagini de servicii clare și o bibliotecă de componente gata pentru predare către dezvoltare."}'::jsonb, 30),
  ('conu-tache', 'Conu''Tache', 'live', 'web', 'ecommerce', '#B4530A', '2022', '[[0,4],[1,2],[2,1]]'::jsonb, '{}'::jsonb, '{"en":"E-Commerce · UX/UI","ru":"Интернет-магазин · UX/UI","ro":"E-Commerce · UX/UI"}'::jsonb, '{"en":"A food & drink e-commerce brand that needed to feel handmade, not templated. I redesigned the storefront around the product photography, rebuilt checkout to cut abandoned carts, and gave it a responsive layout that holds up on mobile.","ru":"E-commerce бренд еды и напитков, которому нужно было выглядеть не как шаблон, а как ручная работа. Я пересобрал витрину вокруг предметной съёмки, переделал чекаут против брошенных корзин и сделал адаптивную вёрстку, которая держится на мобильных.","ro":"Un brand de e-commerce pentru mâncare și băuturi care trebuia să pară lucrat manual, nu templat. Am redesenat vitrina în jurul fotografiei de produs, am reconstruit checkout-ul împotriva coșurilor abandonate și am făcut un layout responsive care ține pe mobil."}'::jsonb, 40),
  ('promez', 'Promez', 'live', 'web', 'ecommerce', '#0E7490', '2021', '[[0,4],[0,0],[1,2]]'::jsonb, '{}'::jsonb, '{"en":"E-Commerce · UX/UI","ru":"Интернет-магазин · UX/UI","ro":"E-Commerce · UX/UI"}'::jsonb, '{"en":"An online store carrying a wide, messy catalogue. I restructured navigation and filtering around how people actually shop, then simplified checkout from five steps to two.","ru":"Интернет-магазин с большим и запутанным каталогом. Я перестроил навигацию и фильтры под реальное поведение покупателей и сократил чекаут с пяти шагов до двух.","ro":"Un magazin online cu un catalog mare și încurcat. Am restructurat navigarea și filtrele după cum cumpără oamenii cu adevărat și am redus checkout-ul de la cinci pași la doi."}'::jsonb, 50),
  ('des-champs', 'Des Champs', 'live', 'web', 'ecommerce', '#4D7C0F', '2020', '[[0,4],[2,1],[1,2]]'::jsonb, '{}'::jsonb, '{"en":"E-Commerce · UX/UI","ru":"Интернет-магазин · UX/UI","ro":"E-Commerce · UX/UI"}'::jsonb, '{"en":"A rebrand-and-rebuild for an online store outgrowing its old identity. New visual system, new storefront, and a checkout flow rebuilt for mobile-first traffic.","ru":"Ребрендинг и пересборка магазина, который перерос старую айдентику. Новая визуальная система, новая витрина и чекаут, пересобранный под mobile-first трафик.","ro":"Rebranding și reconstrucție pentru un magazin care depășise vechea identitate. Sistem vizual nou, vitrină nouă și checkout reconstruit pentru trafic mobile-first."}'::jsonb, 60),
  ('yuca-vpn', 'YUCA VPN', 'live', 'android', 'mobile', '#6D28D9', '2023', '[[1,4],[2,0],[0,7]]'::jsonb, '{}'::jsonb, '{"en":"Android App · Branding & UX/UI","ru":"Android-приложение · Брендинг и UX/UI","ro":"Aplicație Android · Branding & UX/UI"}'::jsonb, '{"en":"An Android VPN app where trust is the whole product. I designed the onboarding, settings architecture and subscription flow, then built the icon and app identity to match - calm, technical, no dark patterns.","ru":"Android-приложение VPN, где доверие - это и есть продукт. Я спроектировал онбординг, архитектуру настроек и флоу подписки, а затем собрал иконку и айдентику под это - спокойно, технично, без тёмных паттернов.","ro":"O aplicație Android de VPN unde încrederea este chiar produsul. Am proiectat onboarding-ul, arhitectura setărilor și fluxul de abonament, apoi am construit iconița și identitatea aplicației pe măsură - calm, tehnic, fără dark patterns."}'::jsonb, 70),
  ('riongo', 'Riongo', 'dev', 'web', 'product', '#FF3B30', '2026', '[[0,7],[0,5],[1,1]]'::jsonb, '{}'::jsonb, '{"en":"UX/UI Design","ru":"UX/UI дизайн","ro":"Design UX/UI"}'::jsonb, '{"en":"An early-stage product still finding its shape. I''m running the UX research and wireframing now, prototyping flows before the visual system locks in - the kind of ambiguous, ground-floor work I like most.","ru":"Продукт на ранней стадии, который ещё ищет свою форму. Сейчас веду UX-исследование и вайрфрейминг, прототипирую флоу до того, как зафиксируется визуальная система - люблю именно такую, неопределённую работу с нуля.","ro":"Un produs la început de drum, care încă își caută forma. Acum fac research UX și wireframing, prototipez fluxurile înainte ca sistemul vizual să se fixeze - genul ăsta de lucru ambiguu, de la zero, îmi place cel mai mult."}'::jsonb, 80),
  ('pawsome-world', 'Pawsome.world', 'dev', 'mobile', 'mobile', '#EA580C', '2026', '[[0,0],[1,1],[2,0]]'::jsonb, '{}'::jsonb, '{"en":"Pets App · UX/UI","ru":"Приложение для питомцев · UX/UI","ro":"Aplicație pentru animale de companie · UX/UI"}'::jsonb, '{"en":"A pet-adoption and rescue marketplace, currently in build. I prototyped the adoption flow end-to-end and I''m shaping the identity system now - this one gets the same rigor as any paid client, pro-bono rate or not.","ru":"Маркетплейс усыновления и помощи животным, сейчас в разработке. Я спрототипировал флоу усыновления от начала до конца и сейчас леплю систему айдентики - этому проекту тот же уровень внимания, что и любому платному, несмотря на тариф pro bono.","ro":"Un marketplace de adopții și salvare a animalelor, momentan în lucru. Am prototipat fluxul de adopție integral și acum construiesc sistemul de identitate - proiectul primește același nivel de atenție ca oricare client plătit, indiferent de tariful pro bono."}'::jsonb, 90),
  ('logos-for-business', 'Logos for Business', 'case', 'print', 'branding', '#0F0F13', '2021', '[[2,0],[2,1],[2,4]]'::jsonb, '{"en":"Logos for Business","ru":"Логотипы для бизнеса","ro":"Logo-uri pentru afaceri"}'::jsonb, '{"en":"Branding · Logos","ru":"Брендинг · Логотипы","ro":"Branding · Logo-uri"}'::jsonb, '{"en":"A running collection of identity work for small businesses across Moldova and the EU - logo systems built to survive a business card, a storefront sign, and a social feed equally well.","ru":"Постоянная коллекция айдентики для малого бизнеса из Молдовы и ЕС - логотипы, которые одинаково хорошо держатся на визитке, на вывеске и в ленте соцсетей.","ro":"O colecție continuă de identitate vizuală pentru afaceri mici din Moldova și UE - sisteme de logo construite să reziste la fel de bine pe o carte de vizită, pe o firmă de magazin și într-un feed de social media."}'::jsonb, 100),
  ('rock-metal-stage-md', 'Rock / Metal Stage MD', 'case', 'print', 'branding', '#0F0F13', '2022', '[[2,0],[2,3],[2,4]]'::jsonb, '{}'::jsonb, '{"en":"Branding · Logos","ru":"Брендинг · Логотипы","ro":"Branding · Logo-uri"}'::jsonb, '{"en":"Branding for Moldova''s rock and metal scene - posters, merch and stage identity for bands and labels who''d rather spend the budget on a real show than a logo redesign, so I keep it fast and cheap without it looking cheap.","ru":"Брендинг для рок- и метал-сцены Молдовы - постеры, мерч и сценическая айдентика для групп и лейблов, которые лучше потратят бюджет на концерт, чем на редизайн логотипа, так что я держу это быстро и недорого, не теряя в качестве.","ro":"Branding pentru scena rock și metal din Moldova - postere, merch și identitate de scenă pentru trupe și case de discuri care preferă să bage bugetul într-un concert adevărat, nu într-un redesign de logo, așa că țin totul rapid și ieftin, fără să arate ieftin."}'::jsonb, 110)
on conflict (slug) do update set
  name          = excluded.name,
  status        = excluded.status,
  platform      = excluded.platform,
  category      = excluded.category,
  hue           = excluded.hue,
  year          = excluded.year,
  chips         = excluded.chips,
  name_i18n     = excluded.name_i18n,
  tags_i18n     = excluded.tags_i18n,
  overview_i18n = excluded.overview_i18n;
